{% set name = "mfrpy" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev:
  git_url: https://github.com/rtmod/mfrpy.git

requirements:
  build:
    - python
    - setuptools

  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - igraph
    - mfrpy

about:
  home: https://github.com/rtmod/mfrpy
